services:
  nginx:
    image: aolda/itda
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./data:/data

  backend:
    image: aolda/itda_backend
    restart: unless-stopped
    network_mode: host
    environment:
      - SPRING_DATASOURCE_URL=${DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_SERVER_BASE-IP=${SERVER_IP}
    volumes:
      - ./data:/data
